os: osx
osx_image: xcode11.3
language: swift
podfile: Podfile
bundle exec pod install
install: make get-deps
script xcodebuild clean build test -workspace "MoviesDB.xcworkspace" -scheme "MoviesDB" -sdk "iphonesimulator" -destination "platform=iOS Simulator,OS=13.3,name=iPhone 8" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO 


